### ISSUE TITLE
How to use react-i18next to make traduction to validation text ?

### ISSUE THREAD

**Issue by moumnimohamed** [sators/react-password-checklist#1]
There is a way to change or translate  messages ?

![Capture](https://user-images.githubusercontent.com/21304554/99900904-fc157e80-2cb2-11eb-81c0-aebdb0815a71.PNG)

**Comment by sators** [comment]
This is a great idea - I'll work on implementing it!

**Comment by SebastienOuellet** [comment]
Please let us know if you are able to implement the possibility to translate. Thx 💯

**Comment by sators** [comment]
This is now available in [version 1.1.0](https://www.npmjs.com/package/react-password-checklist).  Enjoy!
