### ISSUE TITLE
I'd reallly like a way to limit/specify the special characters set to use

### ISSUE THREAD

**Issue by isrplo** [sators/react-password-checklist#17]

**Comment by sators** [comment]
Feel free to submit a pull request containing this functionality.  I would suggest making a prop to pass in the special characters regex, defaulting to the current one on https://github.com/sators/react-password-checklist/blob/master/src/index.tsx#L60 

See https://github.com/sators/react-password-checklist/blob/master/CONTRIBUTING.md

**Comment by sators** [comment]
Now available in v1.5.0
