### ISSUE TITLE
update for react 18

### ISSUE THREAD

**Issue by YellowFlash2012** [sators/react-password-checklist#22]
While resolving: client@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0||~17.0.2" from react-password-checklist@1.3.3
npm ERR! node_modules/react-password-checklist
npm ERR!   react-password-checklist@"*" from the root project

**Comment by sators** [comment]
Fixed in v1.4.0
