### ISSUE TITLE
Incorrect default message for `minLength`

### ISSUE THREAD

**Issue by philip-damra** [sators/react-password-checklist#23]
**Describe the bug**
The default message for the `minLength` rule is "Password has more than `minLength` characters.". The actual evaluation, though is equivalent to "Password has at least `minLength` characters.". 

Basically, if you set the `minLength` prop to e.g. `8`, the message would indicate to the user that they need to have a password that is _more than_ 8 characters. 

**To Reproduce**
1. Use the `minLength` rule
2. See the message telling you that the password length needs to be _longer than_ `minLength` characters

**Expected behavior**
The default message should tell the user the correct number of characters required for the password

**Additional context**
The actual valid/invalid logic is correct, it's just that the default message implies a `password.length > minLength` evaluation, when it's actually `password.length >= minLength`

Finally, thank you for your work on this open-source component. If you agree with my assessment above, I'd be happy to submit a PR for the change.

**Comment by sators** [comment]
Fantastic find @philip-damra - toss up a PR and I'll get it in!

**Comment by sators** [comment]
Fixed in v1.4.3
