### ISSUE TITLE
Catch errors separately 

### ISSUE THREAD

**Issue by Elhamne** [sators/react-password-checklist#32]
I wonder if there is a separate way to catch each rule's error. So I can handle my `password` and `confirmPassword` field separately.

ex. As we get `isValid` in `onChange` prop, we've been able to get each rule's validation status.

Thanks.

**Comment by sators** [comment]
Great idea - submit a PR that passes another argument to the onChange function with the failed rule(s) (and a unit test to prove it) and I'll happily merge that in!

**Comment by sators** [comment]
Now available in v1.5.0
