### ISSUE TITLE
Massively reduce bundle size by omitting styled-components

### ISSUE THREAD

**Issue by SimonHarte** [sators/react-password-checklist#34]
**Is your feature request related to a problem? Please describe.**
Although the library provides exactly what we need in our latest project we opted not to use react-password-checklist simply because it uses styled-components which makes up at least 52% of the bundled size.

**Describe the solution you'd like**
It shouldn't be very complicated to omit styled-components and just use inline styles.

**Describe alternatives you've considered**
You could also provide a css file with the lib that must be imported.

**Additional context**
<img width="1438" alt="image" src="https://github.com/sators/react-password-checklist/assets/691991/bd5bb430-5557-47b7-a305-3d9d23778c4a">
<img width="599" alt="image" src="https://github.com/sators/react-password-checklist/assets/691991/1b6f71b4-6c07-4cb5-8127-5f7641b96d0d">

**Comment by sators** [comment]
Great feedback @SimonHarte - thanks for the discovery.  If you want to post up a PR that accomplishes this, I'd be happy to merge it in and release.  Thanks!

**Comment by tpatel** [comment]
@sators I've just submitted a PR to remove `styled-components`: https://github.com/sators/react-password-checklist/pull/36
