### ISSUE TITLE
Remove Icon

### ISSUE THREAD

**Issue by ztk1296** [sators/react-password-checklist#35]
Hello, 

Thank you for an easy to implement password checklist package. This has simplified several forms and error handling. 
Our current design does not include a icon and I've successfully hidden the icon by setting the iconSize: {0}.

However when I added custom lines that are outside of the provided rules - such as "Please use an original password", the text has to adjust because the hidden icon still populates space for the SVG component. I tried using CSS styling too set display to none for "checklist-icon" but see that it is still displaying with our current design.

I look forward to an update that includes something like:

displayIcon: none

**Comment by sators** [comment]
Cool - good request.  Perhaps either a `hideIcon` prop on the root component, or some logic that if iconSize is 0 to not add the icon at all...ya?  If you want to work up a pull request with tests, I'd be happy to bring it into the fold!

**Comment by ztk1296** [comment]
good insight, I'll add some tests and send over the PR

**Comment by sators** [comment]
Now available in v1.5.0
