### ISSUE TITLE
Possibility to have filter of lowercase and uppercase in one

### ISSUE THREAD

**Issue by 1Bjorn1** [sators/react-password-checklist#44]
Is it possible to make a rule for lowercase and uppercase letters in the same function?

Or maybe have possibility to add onw regex and custom text for that regex.

**Comment by sators** [comment]
Currently that's not supported, but if you want to wire it up and put in a PR for it (with tests) I'd be happy to implement it into the fold!

**Comment by sators** [comment]
This is now available in v1.7
