### ISSUE TITLE
failedRules not behaving as expected

### ISSUE THREAD

**Issue by fmeert** [sators/react-password-checklist#46]
I try to implement the onChange functionality in order to make a distinction between the password that is validated against the password rules and the matching of the password.
The onChange is only triggered if isValid changes. And this only happens if all of the requirements are met, or none of the requirements are met if you start filling in a password.

I would expect, that onChange is triggered if the password is changing from valid to invalid AND if one of the rules changes from being non-compliant with the rule to being compliant with the rule, or from compliant to non compliant.

As it is now, the failedRules are sort of useless, while it could be great functionality in telling the user in depth where something is going wrong

**Comment by sators** [comment]
Good note @fmeert. I'll take a look at improving, or if you want to speed up the process, feel free to queue up a pull request that improves this functionality.

**Comment by sators** [comment]
Actually I found some time this morning to crank this out - fix coming up shortly...

**Comment by fmeert** [comment]
wow! you are fast!! good job

**Comment by sators** [comment]
Fixed and published in v1.5.1 - thanks for the report!
