### ISSUE TITLE
Cannot read properties of null (reading 'useMemo')

### ISSUE THREAD

**Issue by krzysztof-kwiecinski-wttech** [sators/react-password-checklist#52]
**Describe the bug**
After implementing the password checklist for trying it out in my app I am getting an error: 

TypeError: Cannot read properties of null (reading 'useMemo') at ReactPasswordChecklist (index.js:96:31) which refers to 
 ` var enabledRules = useMemo(function () { return rules.filter(function (rule) { return Boolean(ruleDefinitions[rule]); }); }, [rules]);`

I'm using it like this in React app: 
![image](https://github.com/sators/react-password-checklist/assets/90602573/cf060599-4f48-466d-bd20-5da02ca42f35)

**Expected behavior**
Working library

**Desktop (please complete the following information):**
 - iOS

**Comment by sators** [comment]
Hello @krzysztof-kwiecinski-wttech - thanks for reaching out.  Could this be within a Next app and the `PasswordTips` be a server component?  You may need to add a `"use client;"` at the top.  See https://stackoverflow.com/q/72368786/659188

**Comment by krzysztof-kwiecinski-wttech** [comment]
Hi, is quickly opened and quickly closed. Wish I could just delete it as it was a silly thing. I installed it in wrong place and it didn't see React, but somehow my IDE didn't notify me about it. Just checked my React version to see if it's ok and realized that I don't have your package here. 
Sorry!

**Comment by sators** [comment]
All good!  Glad it was something easy!
