### ISSUE TITLE
No spaces check and capitalAndLowerCase  - Feature req

### ISSUE THREAD

**Issue by saver711** [sators/react-password-checklist#54]
Include
1- No spaces check
2- capitalAndLowerCase compined under 1 rule
i am going to borrow your source code until you do it, then i promise i will delete it and use your package
just let me know

**Comment by sators** [comment]
Great thought!  If you put up a PR, I'll merge it in!

**Comment by saver711** [comment]
@sators Done <3

**Comment by sators** [comment]
Reference #55

**Comment by sators** [comment]
This is now available in v1.7
