### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by neutron92** [sators/react-password-checklist#56]
**Describe the bug**
/node_modules/react-password-checklist/dist/index.js:23

import React, { useMemo, useEffect } from "react";

^^^^^^

SyntaxError: Cannot use import statement outside a module

**To Reproduce**
 i installed the module in nextjs 
 npm install --save react-password-checklist

**Comment by sators** [comment]
This has been resolved in v1.8 which is now available.
