### ISSUE TITLE
Trigger noSpaces validation only if the string length > 0

### ISSUE THREAD

**Issue by BRAiNCHiLD95** [sators/react-password-checklist#58]
**Describe the bug**
At the moment, the noSpaces validation is "true" immediately, before the user has even started typing anything.

**To Reproduce**
1. Go to [the codepen](https://codepen.io/BRAiNCHiLD95/pen/eYqZovp)
2. See noSpaces valid by default.

**Expected behavior**
Ideally, the check should happen only after the user starts typing and/or if the length of the input variable is not 0.

**Additional context**
Happy to make the changes and create a PR if you need a dev

**Comment by sators** [comment]
Hi @BRAiNCHiLD95 - thanks for the flag.  A PR would be very welcomed (as well as a test to recreate the present issue!)
