### ISSUE TITLE
Add support for max-length and lowercase letter checks

### ISSUE THREAD

**Issue by philipabc** [sators/react-password-checklist#6]
this is very perfect extension, but I would like:
1 add a function for lowercase
2 add a maximum length
3 if password and password again are empty, there are empty judge

**Comment by sators** [comment]
Hi @philipabc thanks for your feedback - can you expound upon what you mean by "add a function for lowercase"?

**Comment by philipabc** [comment]
thank you for your replying.  
sometimes, users need to check if there is at least one lowercase letter in the password.

**Comment by sators** [comment]
Also, what is your definition of "empty judge"?  The component is a checklist, so would it be a checklist item that turns green/passes when the passwords are not empty?

**Comment by philipabc** [comment]
sorry for confusing, about empty judge, if sometime the user put nothing for input in the form, there is an error.  Thank you adding new features. nice job!

**Comment by philipabc** [comment]
maybe you think it should not be empty, it is ok. because it should not be empty.

**Comment by sators** [comment]
This has been implemented and released in version 1.2.0.

**Comment by philipabc** [comment]
I have checked it , perfect job!!!
