### ISSUE TITLE
New requirement - at least one minus letter validation

### ISSUE THREAD

**Issue by usackoka** [sators/react-password-checklist#7]
Thanks

**Comment by sators** [comment]
Just to clarify here @usackoka - are you suggesting that requiring a lowercase letter should be a validation option?

**Comment by usackoka** [comment]
Yes, for example:

<PasswordChecklist
        rules={['length', 'specialChar', 'number', 'capital', 'match', 'minus']}
        messages={{
                        minus: 'At least one lower case letter.',


is that posible?

**Comment by sators** [comment]
Duplicate of #6
